version: '3.1'

services:
  sql_server:
    container_name: SQLServer2019
    build: 
      context: .
      target: SQL2019
    ports:
      - 20000:1433
    volumes:
      - ./file_db/SQLServer/:/var/opt/mssql/data/
    restart: always
  
  mysql:
    container_name: MySQL8
    build:
      context: .
      target: MySQL8
    ports:
      - 20001:3306
    volumes:
      - ./file_db/mysql/:/var/lib/mysql
    restart: always

  Postgres:
    container_name: Postgres
    build:
      context: .
      target: Postgres
      ports:
      - 20003:5432
      volumes:
      - ./file_db/postgres:/var/lib/postgresql/data 
      restart: always

    Oracle:
    container_name: Oracle9
    build:
      context: .
      target: Oracle9
      ports:
      - 20004:80
    restart: always
